---
# Ansible Galaxy requirements
#
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: ibm.power_hmc
    version: ">=1.0.0"
  # required for ansible.controller setup
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
  - name: infra.aap_configuration
