---
# Ansible inventory for IBM Power infrastructure
#
# This inventory includes:
#   - HMC hosts for managing Power systems
#   - Kickstart servers for provisioning LPARs
#   - Power systems and LPARs

all:
  children:
    # =========================================================================
    # Kickstart Servers
    # =========================================================================
    kickstart_servers:
      hosts:
        mkoch-powerkick:
          ansible_host: "10.32.98.240"
          # Override these variables as needed:
          # dhcp_range_start_override: "10.32.111.1"
          # dhcp_range_end_override: "10.32.111.230"
          dns_server1: "10.32.96.1"
          dns_server2: "10.32.96.31"
          domain_name: "power.coe.muc.redhat.com"
      vars:
        # Explicitly set SSH connection (required when playbook uses connection: local)
        ansible_connection: ssh
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_user: root
        # ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"
    # =========================================================================
    # Bootp Server
    # =========================================================================
    bootp_servers:
      hosts:
        sf1.coe.muc.redhat.com:
          ansible_host: "10.32.96.61"
          dns_server1: "10.32.96.1"
          dns_server2: "10.32.96.31"
          netmask: "255.255.240.0"
          gateway: "10.32.96.1"
          domain_name: "power.coe.muc.redhat.com"
      vars:
        # Explicitly set SSH connection (required when playbook uses connection: local)
        ansible_connection: ssh
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        #ansible_become: true
        ansible_become_method: sudo
        ansible_become_user: root
        # ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASS') }}"


    # ========================================================================
    # HMC Hosts
    # =========================================================================
    hmc:
      hosts:
        # Primary HMC - manages power91 and power92
        10.32.104.241:
          managed_systems_list:
            - "power91"
            - "power92"

        # Secondary HMC (optional) - uncomment if hmc1 is not reachable from the control node
        # 10.32.104.242:
        #   managed_systems_list:
        #     - "power91"
        #     - "power92"

      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_remote_tmp: /tmp/.ansible-${USER}/tmp
        # Default HMC username (can be overridden per host)
        hmc_username: "admin"

        # HMC password - RECOMMENDED: Use ansible-vault or environment variable
        # hmc_pass: "{{ lookup('env', 'HMC_PASSWORD') }}"
